name: Sync All Branches and Tags

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0:00 触发一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          repository: CyrusZhou-CN/Marlin
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Sync all branches
        run: |
          REMOTE_REPO="MarlinFirmware/Marlin"
          LOCAL_REPO="CyrusZhou-CN/Marlin"

          # 获取所有远程分支
          BRANCHES=$(gh api repos/$REMOTE_REPO/branches --jq '.[].name')

          for branch in $BRANCHES; do
            echo "Syncing branch: $branch"
            gh repo sync $LOCAL_REPO -b $branch --force
          done

      - name: Sync all tags
        run: |
          REMOTE_REPO="MarlinFirmware/Marlin"
          LOCAL_REPO="CyrusZhou-CN/Marlin"

          # 获取所有远程标签
          TAGS=$(gh api repos/$REMOTE_REPO/tags --jq '.[].name')

          for tag in $TAGS; do
            echo "Syncing tag: $tag"
            gh repo sync $LOCAL_REPO -t $tag --force
          done
